# Generated by qadiff-dct
# 共通 DB コンテナ管理 Makefile

.PHONY: help db-up db-down db-status db-logs

help:
	@echo "Usage: make <target>"
	@echo ""
	@echo "Shared DB:"
	@echo "  db-up     Start shared PostgreSQL and Redis containers"
	@echo "  db-down   Stop shared DB containers"
	@echo "  db-status Show shared DB container status"
	@echo "  db-logs   Show shared DB container logs"

# ========================================
# 共通 DB コンテナ管理
# ========================================
db-up:
	@bash scripts/db.sh up

db-down:
	@bash scripts/db.sh down

db-status:
	@bash scripts/db.sh status

db-logs:
	@bash scripts/db.sh logs
