#!/bin/bash
# Generated by qadiff-dct
# Firewall initialization script for development containers
# Allows common package registries and development URLs for all major languages

set -e

# Skip if not running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "[init-firewall] Skipping - not running as root"
    exit 0
fi

# Check if iptables is available
if ! command -v iptables &> /dev/null; then
    echo "[init-firewall] iptables not found, skipping firewall setup"
    exit 0
fi

# Skip if already initialized (saves 3-5 seconds on container restart)
MARKER_FILE="/var/run/qadiff-firewall-initialized"
if [ -f "$MARKER_FILE" ]; then
    echo "[init-firewall] Already initialized, skipping"
    exit 0
fi

echo "[init-firewall] Setting up firewall rules..."

# Flush existing rules
iptables -F OUTPUT 2>/dev/null || true

# Allow loopback
iptables -A OUTPUT -o lo -j ACCEPT

# Allow established connections
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Allow DNS
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT

# Allow HTTP/HTTPS
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT

# Allow SSH (for git)
iptables -A OUTPUT -p tcp --dport 22 -j ACCEPT

# ============================================
# Language-specific package registries
# ============================================

# --- JavaScript / Node.js ---
# npm registry
# registry.npmjs.org
# npm.pkg.github.com (GitHub Packages)
# registry.yarnpkg.com

# --- Python ---
# pypi.org
# files.pythonhosted.org
# pypi.python.org

# --- Go ---
# proxy.golang.org
# sum.golang.org
# storage.googleapis.com (module downloads)

# --- Rust ---
# crates.io
# static.crates.io
# index.crates.io

# --- Ruby ---
# rubygems.org
# bundler.rubygems.org

# --- Java / Kotlin / Scala ---
# repo.maven.apache.org
# repo1.maven.org
# jcenter.bintray.com
# plugins.gradle.org
# services.gradle.org

# --- .NET / C# ---
# api.nuget.org
# nuget.org
# dotnetcli.azureedge.net

# --- PHP ---
# repo.packagist.org
# packagist.org
# getcomposer.org

# --- Dart / Flutter ---
# pub.dev
# storage.googleapis.com

# --- Docker ---
# hub.docker.com
# registry-1.docker.io
# auth.docker.io
# production.cloudflare.docker.com
# ghcr.io (GitHub Container Registry)
# mcr.microsoft.com (Microsoft Container Registry)

# --- Git Hosting ---
# github.com
# api.github.com
# raw.githubusercontent.com
# objects.githubusercontent.com
# gitlab.com
# bitbucket.org

# --- Cloud Providers ---
# AWS
# amazonaws.com
# Azure
# azure.com
# azureedge.net
# GCP
# googleapis.com
# storage.googleapis.com

# --- CDNs ---
# cdn.jsdelivr.net
# unpkg.com
# cdnjs.cloudflare.com

# --- Common Dev Tools ---
# api.anthropic.com (Claude API)
# claude.ai (Claude web / installer)
# api.openai.com
# raw.githubusercontent.com

# --- Local Development ---
# Allow connections to common local ports
iptables -A OUTPUT -p tcp -d 127.0.0.0/8 -j ACCEPT
iptables -A OUTPUT -p tcp -d 10.0.0.0/8 -j ACCEPT
iptables -A OUTPUT -p tcp -d 172.16.0.0/12 -j ACCEPT
iptables -A OUTPUT -p tcp -d 192.168.0.0/16 -j ACCEPT

# Allow Docker internal networks
iptables -A OUTPUT -o docker0 -j ACCEPT
iptables -A OUTPUT -o br- -j ACCEPT

echo "[init-firewall] Firewall rules applied successfully"
echo "[init-firewall] All common development URLs are allowed"

# Mark as initialized to skip on container restart
touch "$MARKER_FILE"
