#!/usr/bin/env bash
# Generated by qadiff-dct
# initializeCommand から呼び出され、compose.override.yml を自動生成
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PROJECT_NAME="$(basename "$PROJECT_ROOT")"
OVERRIDE_FILE="$SCRIPT_DIR/compose.override.yml"

# べき等：既存ファイルがあれば何もしない
if [ -f "$OVERRIDE_FILE" ]; then
  echo "[init-compose-override] compose.override.yml already exists, skipping"
  exit 0
fi

# OS検出: mac / win / linux
detect_os() {
  case "$(uname -s)" in
    Darwin)
      echo "mac"
      ;;
    MINGW*|MSYS*|CYGWIN*)
      # Git Bash / MSYS2 / Cygwin on Windows
      echo "win"
      ;;
    Linux)
      # WSL も Linux として検出されるが、WSL は Windows 扱い
      if [ -f /proc/version ] && grep -qi microsoft /proc/version 2>/dev/null; then
        echo "win"
      else
        echo "linux"
      fi
      ;;
    *)
      echo "linux"
      ;;
  esac
}

OS_TYPE="$(detect_os)"
echo "[init-compose-override] Detected OS: $OS_TYPE"

# パス変換関数（Docker Desktop が理解できる形式に変換）
to_docker_path() {
  local path="$1"
  case "$OS_TYPE" in
    win)
      # Windows: /mnt/c/... → C:/... または /c/... → C:/...
      echo "$path" | sed -E 's|^/mnt/([a-zA-Z])/|\U\1:/|; s|^/([a-zA-Z])/|\U\1:/|'
      ;;
    mac|linux)
      # Mac/Linux: そのまま
      echo "$path"
      ;;
  esac
}

# ホームディレクトリを検出
get_host_home() {
  case "$OS_TYPE" in
    win)
      # Windows: USERPROFILE を使用
      if [ -n "${USERPROFILE:-}" ]; then
        # USERPROFILE を Docker パスに変換
        echo "$USERPROFILE" | sed 's|\\|/|g'
      elif command -v cmd.exe >/dev/null 2>&1; then
        # WSL: cmd.exe から USERPROFILE を取得
        cmd.exe /c "echo %USERPROFILE%" 2>/dev/null | tr -d '\r\n' | sed 's|\\|/|g'
      else
        echo ""
      fi
      ;;
    mac|linux)
      echo "${HOME:-}"
      ;;
  esac
}

HOST_HOME="$(get_host_home)"
if [ -z "$HOST_HOME" ]; then
  echo "Error: Cannot detect home directory" >&2
  exit 1
fi

# Docker Desktop 用のパスに変換
DOCKER_PROJECT_ROOT="$(to_docker_path "$PROJECT_ROOT")"
DOCKER_HOST_HOME="$(to_docker_path "$HOST_HOME")"

echo "[init-compose-override] Project root: $DOCKER_PROJECT_ROOT"
echo "[init-compose-override] Host home: $DOCKER_HOST_HOME"

# compose.override.yml を生成
cat > "$OVERRIDE_FILE" << EOF
# Generated by init-compose-override.sh
# This file is gitignored - each user's environment is different
# OS: $OS_TYPE
services:
  dev:
    volumes:
      - ${DOCKER_PROJECT_ROOT}:/workspaces/${PROJECT_NAME}:cached
      - ${DOCKER_HOST_HOME}/.claude:/home/vscode/.claude
      - ${DOCKER_HOST_HOME}/.ssh:/home/vscode/.ssh:ro
EOF

echo "[init-compose-override] Created: $OVERRIDE_FILE"
