#!/usr/bin/env bash
set -euo pipefail

echo "[postCreate] start"

# Note: Common tools (jq, unzip, ca-certificates, curl, git) are pre-installed in Dockerfile.
# Do NOT add apt-get install here - it duplicates work and adds 30-50 seconds to startup.

# Optional: load proxy settings from a local file (recommended for corporate networks)
# Create .devcontainer/.env with e.g.:
#   HTTPS_PROXY=http://proxy.example.com:8080
#   HTTP_PROXY=http://proxy.example.com:8080
#   NO_PROXY=localhost,127.0.0.1
set +e
load_proxy_env_file() {
	env_file=".devcontainer/.env"
	[ -f "$env_file" ] || return 0

	echo "[postCreate] loading proxy env from $env_file"
	while IFS= read -r line; do
		case "$line" in
			""|\#*) continue ;;
		esac
		key="${line%%=*}"
		val="${line#*=}"
		case "$key" in
			HTTP_PROXY|http_proxy|HTTPS_PROXY|https_proxy|NO_PROXY|no_proxy|ALL_PROXY|all_proxy)
				export "$key=$val"
				;;
		esac
	done < "$env_file"
}

persist_proxy_env() {
	# Persist for interactive shells (claude, git, npm, etc.)
	# Avoid failing the container if sudo is not available.
	if ! command -v sudo >/dev/null 2>&1; then
		return 0
	fi
	sudo -n true >/dev/null 2>&1 || return 0

	if [ -n "${HTTP_PROXY:-}" ] || [ -n "${HTTPS_PROXY:-}" ] || [ -n "${NO_PROXY:-}" ] || [ -n "${ALL_PROXY:-}" ] || \
		 [ -n "${http_proxy:-}" ] || [ -n "${https_proxy:-}" ] || [ -n "${no_proxy:-}" ] || [ -n "${all_proxy:-}" ]; then
		sudo tee /etc/profile.d/qadiff-proxy.sh >/dev/null <<'EOF'
# Generated by qadiff-dct (postCreate)
# Proxy env passthrough for corporate networks
export HTTP_PROXY="${HTTP_PROXY}"
export http_proxy="${http_proxy}"
export HTTPS_PROXY="${HTTPS_PROXY}"
export https_proxy="${https_proxy}"
export NO_PROXY="${NO_PROXY}"
export no_proxy="${no_proxy}"
export ALL_PROXY="${ALL_PROXY}"
export all_proxy="${all_proxy}"
EOF
		echo "[postCreate] proxy env persisted to /etc/profile.d/qadiff-proxy.sh"
	fi
}

load_proxy_env_file
persist_proxy_env
set -e

# Git configuration cleanup for Dev Containers
# VS Code auto-forwards the host's .gitconfig, but Windows-specific paths don't work in Linux containers.
# We preserve essential settings (user.name, user.email) and remove problematic Windows paths.
set +e
if command -v git >/dev/null 2>&1; then
	echo "[postCreate] cleaning up git config for container environment..."

	# 1. Remove Windows-style safe.directory entries
	while IFS= read -r sd; do
		case "$sd" in
			[A-Za-z]:/*|[A-Za-z]:\\*)
				git config --global --unset-all safe.directory "$sd" >/dev/null 2>&1
				echo "[postCreate] removed invalid git safe.directory: $sd"
				;;
		esac
	done <<EOF
$(git config --global --get-all safe.directory 2>/dev/null)
EOF

	# 2. Remove GPG/signing settings with Windows paths
	signingkey="$(git config --global --get user.signingkey 2>/dev/null || true)"
	gpg_program="$(git config --global --get gpg.program 2>/dev/null || true)"

	case "$signingkey" in
		[A-Za-z]:/*|[A-Za-z]:\\*)
			git config --global --unset user.signingkey 2>/dev/null
			echo "[postCreate] removed Windows-path user.signingkey: $signingkey"
			;;
	esac

	case "$gpg_program" in
		[A-Za-z]:/*|[A-Za-z]:\\*|*".exe")
			git config --global --unset gpg.program 2>/dev/null
			echo "[postCreate] removed Windows gpg.program: $gpg_program"
			;;
	esac

	# 3. Setup SSH commit signing (preferred for DevContainers)
	# SSH Agent forwarding allows signing without GPG installation
	setup_ssh_signing() {
		# Find SSH public key
		local ssh_pubkey=""
		for key in "$HOME/.ssh/id_ed25519.pub" "$HOME/.ssh/id_rsa.pub" "$HOME/.ssh/id_ecdsa.pub"; do
			if [ -f "$key" ]; then
				ssh_pubkey="$key"
				break
			fi
		done

		if [ -z "$ssh_pubkey" ]; then
			echo "[postCreate] no SSH public key found, disabling commit signing"
			git config --global commit.gpgsign false 2>/dev/null
			return
		fi

		# Check if SSH Agent is available
		if [ -z "${SSH_AUTH_SOCK:-}" ]; then
			echo "[postCreate] SSH Agent not available, disabling commit signing"
			git config --global commit.gpgsign false 2>/dev/null
			return
		fi

		# Configure SSH signing
		git config --global gpg.format ssh 2>/dev/null
		git config --global user.signingkey "$ssh_pubkey" 2>/dev/null
		git config --global commit.gpgsign true 2>/dev/null
		git config --global tag.gpgsign true 2>/dev/null
		echo "[postCreate] SSH commit signing enabled with key: $ssh_pubkey"
	}

	# Only setup signing if it was enabled on host (or user wants signing)
	host_gpgsign="$(git config --global --get commit.gpgsign 2>/dev/null || true)"
	if [ "$host_gpgsign" = "true" ] || [ -n "$signingkey" ]; then
		setup_ssh_signing
	else
		echo "[postCreate] commit signing not enabled on host, skipping"
	fi

	# 4. Remove Windows-specific core settings
	core_editor="$(git config --global --get core.editor 2>/dev/null || true)"
	case "$core_editor" in
		*".exe"*|[A-Za-z]:/*|[A-Za-z]:\\*)
			git config --global --unset core.editor 2>/dev/null
			echo "[postCreate] removed Windows core.editor: $core_editor"
			;;
	esac

	credential_helper="$(git config --global --get credential.helper 2>/dev/null || true)"
	case "$credential_helper" in
		*"manager"*|*".exe"*)
			git config --global --unset credential.helper 2>/dev/null
			echo "[postCreate] removed Windows credential.helper: $credential_helper"
			;;
	esac

	# 5. Add safe.directory for current workspace
	current_dir="$(pwd -P 2>/dev/null)"
	workspace_root=""
	if [ -n "$current_dir" ]; then
		case "$current_dir" in
			/workspaces/*)
				workspace_root="$(printf "%s" "$current_dir" | sed -E 's|^(/workspaces/[^/]+).*|\1|')"
				;;
		esac
	fi

	if [ -n "$workspace_root" ]; then
		existing="$(git config --global --get-all safe.directory 2>/dev/null)"
		printf "%s\n" "$existing" | grep -Fx "$workspace_root" >/dev/null 2>&1
		if [ $? -ne 0 ]; then
			git config --global --add safe.directory "$workspace_root" 2>/dev/null
			echo "[postCreate] git safe.directory added: $workspace_root"
		else
			echo "[postCreate] git safe.directory already set: $workspace_root"
		fi
	else
		echo "[postCreate] git safe.directory skipped (not under /workspaces)"
	fi

	echo "[postCreate] git config cleanup complete"
else
	echo "[postCreate] git config cleanup skipped (git not installed)"
fi
set -e

# stack: node

echo "[postCreate] node stack selected"


# services: (none)


echo "[postCreate] done"
